Upgrade memmap2 version (#3021)
`maturin` fails on build on AIX due to the following:
```
error[E0308]: mismatched types
    --> /home/amyk/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/memmap2-0.9.9/src/unix.rs:429:30
     |
 429 |             if libc::madvise(self.ptr.offset(offset), len, advice) != 0 {
     |                ------------- ^^^^^^^^^^^^^^^^^^^^^^^ expected `*mut u8`, found `*mut c_void`
     |                |
     |                arguments to this function are incorrect
     |
     = note: expected raw pointer `*mut u8`
                found raw pointer `*mut c_void`
note: function defined here
    --> /home/amyk/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/libc-0.2.180/src/unix/aix/mod.rs:3010:12
     |
3010 |     pub fn madvise(addr: caddr_t, len: size_t, advice: c_int) -> c_int;
     |            ^^^^^^^

```
This issue is resolved thanks to
https://github.com/RazrFalcon/memmap2-rs/commit/d2054a2c9225b8b89968a0f49d10aaed9ff76367,
which is available in v0.9.10.