Upgrade jobserver (#2635)
The new version of libc in
https://github.com/PyO3/maturin/commit/90b30a4e94e58e8d77d5d663cd2e0bbaab933f33
exposes a problem in jobserver, causing build failures on AIX:
```
error[E0609]: no field `sa_union` on type `sigaction`
   --> /home/jenkins/workspace/Rust/Crates/maturin/cargo/registry/src/index.crates.io-7f555b6b8ccf4919/jobserver-0.1.32/src/unix.rs:399:17
    |
399 |             new.sa_union.__su_sigaction = sigusr1_handler;
    |                 ^^^^^^^^ unknown field
    |
    = note: available fields are: `sa_sigaction`, `sa_mask`, `sa_flags`
```

 Update to the latest jobserver which has a fix.