Error messages for bad cargo/rust environment during PEP517 install
The error output from pip is otherwise not understandable by
a user who does not know this package needs Rust or what Rust is.

  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... error
    ERROR: Complete output from command ... pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel ...
    ERROR: 💥 pyo3-pack failed
    Cargo metadata failed: No such file or directory (os error 2)
    ...
    subprocess.CalledProcessError: Command '['pyo3-pack', 'pep517', 'write-dist-info', ... ' returned non-zero exit status 1