`--profile` conflicts with `--release` (and/or `--debug`) (#2793)
This makes `maturin` behave like `cargo` when passing `--release
--profile dev`, e.g.

```
$ cargo build --release --profile dev
error: the argument '--release' cannot be used with '--profile <PROFILE-NAME>'
```

we now get similar from `maturin`

```
$ cargo run -- build --release --profile dev
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.28s
     Running `target/debug/maturin build --release --profile dev`
error: the argument '--release' cannot be used with '--profile <PROFILE-NAME>'
```